### ISSUE TITLE
it support ETS6 ??

### ISSUE THREAD

**Issue by crazy-cpu** [robertguetzkow/ets5-password-recovery#1]

**Comment by robertguetzkow** [comment]
The tool does not work well with projects from the ETS6 , since the XML structure changed. It was just a quick proof of concept rather than a polished software. However, the general concept still works and you will be able to deobfuscate/decrypt the values from the XML files as described in the [README.md](https://github.com/robertguetzkow/ets5-password-recovery/blob/main/README.md#how-does-the-password-recovery-work).

I might develop a more polished version that works for the ETS6 in the future, but I'm not sure when/if I will have time to do so.
